"""Post-mortem scenarios: load the authored taxonomy, resolve each to a frame series, emit
site/data/scenario_<slug>.json, and generate the post-mortem pages + index. Narrative and
classification are authored in data/scenarios.json; every instrument figure is generated by
engine.snapshot from the settled stores (parity-locked). No modelled numbers on instruments.
"""
from __future__ import annotations

import json
from pathlib import Path

from engine.guards import require

SCENARIOS_PATH = Path("data/scenarios.json")
_PANELS = {"reliability", "wind", "solar", "imports", "price"}
_REQUIRED = ("slug", "title", "category", "event_date", "window", "hero", "commentary",
             "panels", "basis")


def load_scenarios(path: Path = SCENARIOS_PATH) -> list[dict]:
    return json.loads(Path(path).read_text())["scenarios"]


def validate_scenario(s: dict) -> None:
    for k in _REQUIRED:
        require(k in s, f"scenario missing key {k!r}")
    require(set(s["panels"]) <= _PANELS, f"scenario {s.get('slug')}: unknown panel")
    require(s["basis"] in ("national", "transmission"), f"scenario {s['slug']}: bad basis")
    for k in ("from", "to"):
        require(k in s["window"], f"scenario {s['slug']}: window missing {k!r}")
    for c in s["commentary"]:
        require(1 <= c["period"] <= 50, f"scenario {s['slug']}: commentary period {c['period']}")
        for k in ("marker", "label", "text"):
            require(k in c, f"scenario {s['slug']}: commentary missing {k!r}")
    for k in ("kicker", "dek", "body_md", "attributed_figures"):
        require(k in s["hero"], f"scenario {s['slug']}: hero missing {k!r}")
