"""Post-mortem scenarios: load the authored taxonomy, resolve each to a frame series, emit
site/data/scenario_<slug>.json, and generate the post-mortem pages + index. Narrative and
classification are authored in data/scenarios.json; every instrument figure is generated by
engine.snapshot from the settled stores (parity-locked). No modelled numbers on instruments.
"""
from __future__ import annotations

import json
from pathlib import Path

from engine import snapshot
from engine.guards import require

SCENARIOS_PATH = Path("data/scenarios.json")
_PANELS = {"reliability", "wind", "solar", "imports", "price"}
_REQUIRED = ("slug", "title", "category", "event_date", "window", "hero", "commentary",
             "panels", "basis")


def load_scenarios(path: Path = SCENARIOS_PATH) -> list[dict]:
    return json.loads(Path(path).read_text())["scenarios"]


def validate_scenario(s: dict) -> None:
    for k in _REQUIRED:
        require(k in s, f"scenario missing key {k!r}")
    require(set(s["panels"]) <= _PANELS, f"scenario {s.get('slug')}: unknown panel")
    require(s["basis"] in ("national", "transmission"), f"scenario {s['slug']}: bad basis")
    for k in ("from", "to"):
        require(k in s["window"], f"scenario {s['slug']}: window missing {k!r}")
    for c in s["commentary"]:
        for k in ("period", "marker", "label", "text"):
            require(k in c, f"scenario {s['slug']}: commentary missing {k!r}")
        require(1 <= c["period"] <= 50, f"scenario {s['slug']}: commentary period {c['period']}")
    for k in ("kicker", "dek", "body_md", "attributed_figures"):
        require(k in s["hero"], f"scenario {s['slug']}: hero missing {k!r}")


def resolve_payload(scenario: dict, *, fuelhh_rows, embedded_rows, price_rows,
                    ns, caps, generated_utc: str) -> dict:
    w = scenario["window"]
    frames = snapshot.extract_series(w["from"], w["to"], fuelhh_rows=fuelhh_rows,
                                     embedded_rows=embedded_rows, price_rows=price_rows,
                                     ns=ns, caps=caps)
    sp_to_index = {f["sp"]: i for i, f in enumerate(frames)}
    markers = [{"index": sp_to_index[c["period"]], "label": c["label"]}
               for c in scenario["commentary"]
               if c["marker"] and c["period"] in sp_to_index]
    return {
        "slug": scenario["slug"], "title": scenario["title"],
        "category": scenario["category"], "event_date": scenario["event_date"],
        "basis": scenario["basis"], "generated_utc": generated_utc,
        "hero": scenario["hero"], "commentary": scenario["commentary"],
        "panels": scenario["panels"], "sources": scenario.get("sources", []),
        "frames": frames, "markers": markers,
    }


def guard_payload(payload: dict) -> None:
    frames = payload["frames"]
    require(len(frames) > 0, f"scenario {payload.get('slug')}: no frames")
    for f in frames:
        require(0.0 <= f["firm_pct"] <= 120.0, f"firm_pct {f['firm_pct']} out of [0,120]")
        require(f["demand_mw"] > 0, "non-positive demand in a frame")
    if "price" in payload["panels"]:
        require(any(f["price_gbp_mwh"] is not None for f in frames), "price panel but no price data")
    if "solar" in payload["panels"]:
        require(any(f["solar_cf_pct"] is not None for f in frames), "solar panel but no solar data")
    for m in payload["markers"]:
        require(0 <= m["index"] < len(frames), f"marker index {m['index']} out of range")
