"""Post-mortem scenarios: load the authored taxonomy, resolve each to a frame series, emit
site/data/scenario_<slug>.json, and generate the post-mortem pages + index. Narrative and
classification are authored in data/scenarios.json; every instrument figure is generated by
engine.snapshot from the settled stores (parity-locked). No modelled numbers on instruments.
"""
from __future__ import annotations

import html as _htmlmod
import json
import sys
from pathlib import Path

from engine import chrome, snapshot
from engine.build_site import _atomic_write
from engine.guards import require

SCENARIOS_PATH = Path("data/scenarios.json")
_PANELS = {"reliability", "wind", "solar", "imports", "price"}
_REQUIRED = ("slug", "title", "category", "event_date", "window", "hero", "commentary",
             "panels", "basis")


def load_scenarios(path: Path = SCENARIOS_PATH) -> list[dict]:
    return json.loads(Path(path).read_text())["scenarios"]


def validate_scenario(s: dict) -> None:
    for k in _REQUIRED:
        require(k in s, f"scenario missing key {k!r}")
    require(set(s["panels"]) <= _PANELS, f"scenario {s.get('slug')}: unknown panel")
    require(s["basis"] in ("national", "transmission"), f"scenario {s['slug']}: bad basis")
    for k in ("from", "to"):
        require(k in s["window"], f"scenario {s['slug']}: window missing {k!r}")
    for c in s["commentary"]:
        for k in ("period", "marker", "label", "text"):
            require(k in c, f"scenario {s['slug']}: commentary missing {k!r}")
        require(1 <= c["period"] <= 50, f"scenario {s['slug']}: commentary period {c['period']}")
    for k in ("kicker", "dek", "body_md", "attributed_figures"):
        require(k in s["hero"], f"scenario {s['slug']}: hero missing {k!r}")


def resolve_payload(scenario: dict, *, fuelhh_rows, embedded_rows, price_rows,
                    ns, caps, generated_utc: str) -> dict:
    w = scenario["window"]
    frames = snapshot.extract_series(w["from"], w["to"], fuelhh_rows=fuelhh_rows,
                                     embedded_rows=embedded_rows, price_rows=price_rows,
                                     ns=ns, caps=caps)
    sp_to_index = {f["sp"]: i for i, f in enumerate(frames)}
    markers = [{"index": sp_to_index[c["period"]], "label": c["label"]}
               for c in scenario["commentary"]
               if c["marker"] and c["period"] in sp_to_index]
    return {
        "slug": scenario["slug"], "title": scenario["title"],
        "category": scenario["category"], "event_date": scenario["event_date"],
        "basis": scenario["basis"], "generated_utc": generated_utc,
        "hero": scenario["hero"], "commentary": scenario["commentary"],
        "panels": scenario["panels"], "sources": scenario.get("sources", []),
        "frames": frames, "markers": markers,
    }


def guard_payload(payload: dict) -> None:
    frames = payload["frames"]
    require(len(frames) > 0, f"scenario {payload.get('slug')}: no frames")
    for f in frames:
        require(0.0 <= f["firm_pct"] <= 120.0, f"firm_pct {f['firm_pct']} out of [0,120]")
        require(f["demand_mw"] > 0, "non-positive demand in a frame")
    if "price" in payload["panels"]:
        require(any(f["price_gbp_mwh"] is not None for f in frames), "price panel but no price data")
    if "solar" in payload["panels"]:
        require(any(f["solar_cf_pct"] is not None for f in frames), "solar panel but no solar data")
    for m in payload["markers"]:
        require(0 <= m["index"] < len(frames), f"marker index {m['index']} out of range")


_IN_SITE_LINKS = ("methodology.html", "about.html", "share.html", "import.html", "wind.html")


def _relativise(html: str, prefix: str) -> str:
    """Point chrome's root-level in-site links at the parent folder for a subfolder page."""
    out = html
    for name in _IN_SITE_LINKS:
        out = out.replace(f'href="{name}"', f'href="{prefix}{name}"')
    return out


def _page_html(payload: dict) -> str:
    esc = _htmlmod.escape
    hero = payload["hero"]
    head = chrome.ASSETS
    header = _relativise(chrome._header("post-mortem"), "../")
    footer = _relativise(chrome.FOOTER, "../")
    attributed = "".join(
        f'<p class="attributed"><strong>{esc(a["value"])}</strong> — {esc(a["label"])} '
        f'<span class="src">({esc(a["source"])})</span></p>'
        for a in hero["attributed_figures"])
    return f"""<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(payload['title'])} — Grid Margin</title>
<meta name="description" content="{esc(hero['dek'])}">
<link rel="canonical" href="https://gridmargin.co.uk/post-mortem/{esc(payload['slug'])}">
{head}
<link rel="stylesheet" href="../postmortem.css">
</head>
<body>
{header}
<main id="main" class="container postmortem" data-slug="{esc(payload['slug'])}">
  <section class="pm-hero">
    <p class="eyebrow">Post-mortem · {esc(hero['kicker'])}</p>
    <h1 class="headline">{esc(payload['title'])}</h1>
    <p class="def pm-dek">{esc(hero['dek'])}</p>
    <div class="pm-body">{esc(hero['body_md'])}</div>
    {attributed}
  </section>
  <section class="pm-instrument" aria-label="Reconstruction of {esc(payload['event_date'])}">
    <div id="pm-player" data-loading>Loading the reconstruction…</div>
  </section>
</main>
{footer}
<script type="module" src="../postmortem.js"></script>
</body>
</html>
"""


def _index_html(payloads: list[dict]) -> str:
    esc = _htmlmod.escape
    items = "".join(
        f'<li><a href="{esc(p["slug"])}.html"><span class="pm-cat">{esc(p["category"])}</span>'
        f'<span class="pm-title">{esc(p["title"])}</span>'
        f'<span class="pm-date">{esc(p["event_date"])}</span></a></li>'
        for p in payloads)
    header = _relativise(chrome._header("post-mortem"), "../")
    footer = _relativise(chrome.FOOTER, "../")
    return f"""<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Post-mortems — Grid Margin</title>
{chrome.ASSETS}
<link rel="stylesheet" href="../postmortem.css">
</head>
<body>
{header}
<main id="main" class="container">
  <h1 class="headline">Post-mortems</h1>
  <p class="def">Reconstructions of past events on the GB grid, played back half-hour by half-hour from the settled record.</p>
  <ul class="pm-index">{items}</ul>
</main>
{footer}
</body>
</html>
"""


def generate_pages(payloads: list[dict], site: Path = Path("site")) -> list[Path]:
    out_dir = site / "post-mortem"
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for p in payloads:
        path = out_dir / f"{p['slug']}.html"
        _atomic_write(path, _page_html(p))
        written.append(path)
    _atomic_write(out_dir / "index.html", _index_html(payloads))
    return written


def build_all(fuelhh_rows, embedded_rows, price_rows, ns, caps, generated_utc,
              site: Path = Path("site")) -> list[tuple[str, dict]]:
    covered_dates = {r["settlement_date"] for r in embedded_rows}
    payloads, named = [], []
    for s in load_scenarios():
        validate_scenario(s)
        if s["window"]["to"] not in covered_dates and s["basis"] == "national":
            print(f"scenario {s['slug']}: window not covered by embedded store — skipping",
                  file=sys.stderr)
            continue
        p = resolve_payload(s, fuelhh_rows=fuelhh_rows, embedded_rows=embedded_rows,
                            price_rows=price_rows, ns=ns, caps=caps, generated_utc=generated_utc)
        guard_payload(p)
        payloads.append(p)
        named.append((f"scenario_{s['slug']}", p))
    if payloads:
        generate_pages(payloads, site=site)
    return named
